name: github pages

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./packages/ui

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: npm ci && npm run docz:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .docz/public
